name: ai-app
services:
- name: api
  github:
    repo: your-repo
    branch: main
    deploy_on_push: true
  source_dir: api
  dockerfile_path: Dockerfile
  http_port: 8000
  instance_size_slug: professional-2xl  # Adjust based on model size
  envs:
  - key: MODEL_PATH
    value: facebook/opt-125m
  - key: PYTORCH_CUDA_ALLOC_CONF
    value: max_split_size_mb:32

- name: client
  github:
    repo: your-repo
    branch: main
    deploy_on_push: true
  source_dir: client
  dockerfile_path: Dockerfile
  instance_size_slug: basic-xxs 