name: geppetto
services:
- name: geppetto-api
  github:
    repo: git@github.com:xnorkl/Geppetto.git
    branch: dev-api
    deploy_on_push: true
  source_dir: src/geppetto_api
  dockerfile_path: Dockerfile
  http_port: 8000
  instance_size_slug: professional-2xl  # Adjust based on model size
  envs:
  - key: MODEL_PATH
    value: facebook/opt-125m
  - key: PYTORCH_CUDA_ALLOC_CONF
    value: max_split_size_mb:32

- name: geppetto-client
  github:
    repo: git@github.com:xnorkl/Geppetto.git
    branch: dev-client
    deploy_on_push: true
  source_dir: client
  dockerfile_path: Dockerfile
  instance_size_slug: basic-xxs 