version: '3.8'

services:
  api:
    build:
      context: ./api
      target: production
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - ENVIRONMENT=development
      - MODEL_PATH=facebook/opt-125m 