version: '3.8'

services:
  geppetto-api:
    build:
      context: ./src/geppetto_api
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - ENVIRONMENT=development
      - MODEL_PATH=facebook/opt-125m 